font=JetBrainsMono Nerd Font 10
background-color=#1e1e2e
text-color=#cdd6f4
border-color=#b4befe
border-size=2
border-radius=10
padding=10
default-timeout=6000
max-visible=4

[urgency=high]
border-color=#f38ba8
default-timeout=0
