add_newline = false
format = "$directory$git_branch$git_status$cmd_duration$character"

[directory]
style = "bold #89b4fa"
truncation_length = 3

[git_branch]
symbol = " "
style = "#cba6f7"

[git_status]
style = "#f9e2af"

[cmd_duration]
min_time = 2000
style = "#a6adc8"

[character]
success_symbol = "[❯](bold #a6e3a1)"
error_symbol = "[❯](bold #f38ba8)"
